config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'landing_page#index'

	get 'news' => 'news#index'
	get 'preferences' => 'preferences#index'
	get 'home' => 'home#index'
	
	resources :articles 
	resources :notes
	resources :reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user
	has_many :reviews

	def first_three_lines
		body.split("\n")[0..2].join("\n")
	end

end

app/models/note.rb
class Note < ApplicationRecord

	belongs_to :user

end

app/models/preference.rb
class Preference < ApplicationRecord

	belongs_to :user

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :article

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :timeout_in => 15.minutes

  validates :username, :presence => true, :uniqueness => true

  has_many :articles
  has_many :notes
  has_many :reviews
  has_one :preference

  def sort_notes_by_id
 		notes = self.notes
 		notes.sort_by{|note| note.id }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
		@reviews = Review.all
		@new_review = Review.new
	end

	def new
		@article = Article.new
	end

	def create
		current_user.articles.create(article_params)
		redirect_to articles_path
	end

	def show
		@article = Article.find(params[:id])
	end

	private

	def article_params
		params.require(:article).permit(:body)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController

	def index
		if user_signed_in?
			redirect_to home_path 
		else
			redirect_to news_path
		end
	end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	def index
		@news_sources = HTTParty.get("https://newsapi.org/v1/sources?language=en&apiKey=#{ENV['NEWS_KEY']}")['sources']
		
	end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def index
		redirect_to root_path if !user_signed_in?
		@sorted_notes = current_user.sort_notes_by_id unless !user_signed_in?
		@note = Note.new
	end

	def create
		current_user.notes.create(create_note_params)
		redirect_to notes_path
	end

	def destroy
		note = current_user.notes.find(params[:id])
		note.delete
		redirect_to notes_path
	end

	def update
		note = current_user.notes.find(edit_note_params[:id])
		note.update(body: edit_note_params[:note])
	end

	private

	def create_note_params
		params.require(:note).permit(:body)
	end

	def edit_note_params
		params.permit(:note, :id)
	end

end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

	def index
		redirect_to root_path if !user_signed_in?
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
	end

	def new
	end

	def create
		current_user.reviews.create(review_params)
		redirect_to articles_path
	end

	private

	def review_params
		params.permit(:review, :rating, :article_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/news_helper.rb
module NewsHelper

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/articles/index.html.erb
<% @articles.each do |article| %>	
		
	<p> <%=link_to 'Read Full Article', article_path(article) %> </p>	
	<p> <%= article.first_three_lines %> </p>
	
	<% if user_signed_in? %>
		<p id="review_form">
			<span>Leave a review</span>
 				
 				<%= form_for @new_review, url: reviews_path do |f| %>
					<textarea name='review'></textarea>					
					
					<select name="rating">
						<% x=1 %>
						<% 10.times do %>
							<option value=<%= x %>><%= x %></option>
							<% x+=1 %>
						<% end %>
					</select>
					
					<input type="hidden" name="article_id" value=<%=article.id%>>
					<input type="submit" value="Submit">
				<% end %>

			</p>
		<% end %>
	
	<p>
		<% @reviews.each do |review| %>
			<% if review.article_id == article.id %>
				<%= review.rating %>
				<%= review.review %>
			<% end %>
		<% end %>
	</p>

<% end %>

<% if user_signed_in? %>
	<%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<%= tinymce_assets %>

<%= form_for @article do |f| %>
  <%= f.text_area :body, class: "tinymce" %>
  <%= f.submit 'Save', id: 'save-button' %>
<% end %> 

<%= tinymce %>

app/views/articles/show.html.erb
	<p> <%= @article.title %> </p>
	<p> <%= @article.body %> </p>

app/views/home/index.html.erb
<% if user_signed_in? %>
	<%= current_user.username %> 
<% end %>

app/views/landing_page/index.html.erb
<div>
	<h3> Overview </h3>
		<p>
			This project is targeted at Journalists and Media Outlets. It's purpose is to create a single, easy to navigate space where users can save their preferences to display custom news feeds from multiple outlets on a homepage. As a writer the user can create and save articles or notes to their profile for convenience. These articles can be searched, browsed and reviewed by all other users for feedback, unless the writer gives the article private status(to keep their ideas secret!), or commercial status(so that registered media outlets can see them). Media Outlets can search for articles or writers by topic if they need to commission a story or to find new talent.
		</p>

	<h3> Technologies used </h3>
		<ul>
			<li> Ruby on Rails with a Postgres database and Rspec & Capybara testing framework </li>
			<li> tinyMCE text-editor </li>
			<li> Travis CI and Coveralls </li>
			<li> Figaro gem for hiding secrets </li>
			<li> Shoulda-matchers gem for testing associations with Rspec </li>
		</ul>

	To see a full list of existing and planned features, <a href='https://github.com/MaxProvin/story-box/blob/master/user_stories.md'>click here</a>
</div>

app/views/news/index.html.erb
<table id='news'>
	
	<% @news_sources.each_slice(5) do |slice| %>
		
		<tr>
			<% slice.each do |s| %>

				<td class='source-info'>
					<span class='news-images' onclick="setIframe(this, '<%=s['url']%>')">
 						<img src=<%=s['urlsToLogos']['small']%> alt="<%=s['name']%>" >
 					</span>
 					<p>
 						<%= s['description'] %>
 					</p>
				</td>

			<% end %>
		</tr>

	<% end %>

</table>

app/views/notes/index.html.erb
<div class='sticky-notes'>
	
	<%= form_for @note, url: {action: "create"} do |f| %>
		<%= f.text_area :body, class: 'notes-box' %>
		<%= f.submit html: {id:'new-note'} %>
	<% end %>

	<% note_num = 1 %>
	<% @sorted_notes.each do |note| %>
		
		<div class='notes'>
			<%= link_to image_tag('red-x.png'), note_path(note), class: 'delete-note', method: :delete %>

			<div contenteditable="true" id=<%="#{note.id}"%> >				
				<%= note.body %>
			</div>
		</div>
		
		<% note_num += 1 %>
	<% end %>

</div>