config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'landing_page#index'

	get 'news' => 'news#index'
	get 'preferences' => 'preferences#index'
	get 'home' => 'home#index'
	
	resources :articles 
	resources :notes
	resources :reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user
	has_many :reviews

	def first_three_lines
		body.split("\n")[0..2].join("\n")
	end

end

app/models/note.rb
class Note < ApplicationRecord

	belongs_to :user

end

app/models/preference.rb
class Preference < ApplicationRecord

	belongs_to :user

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :article

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :timeout_in => 15.minutes

  validates :username, :presence => true, :uniqueness => true

  has_many :articles
  has_many :notes
  has_many :reviews
  has_one :preference

  def sort_notes_by_id
 		notes = self.notes
 		notes.sort_by{|note| note.id }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
		@reviews = Review.all
		@new_review = Review.new
	end

	def new
		@article = Article.new
	end

	def create
		current_user.articles.create(article_params)
		redirect_to articles_path
	end

	def show
		@article = Article.find(params[:id])
	end

	private

	def article_params
		params.require(:article).permit(:body)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	def index
		@news_sources = HTTParty.get("https://newsapi.org/v1/sources?language=en&apiKey=#{ENV['NEWS_KEY']}")['sources']
		
	end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def index
		redirect_to root_path if !user_signed_in?
		@sorted_notes = current_user.sort_notes_by_id unless !user_signed_in?
		@note = Note.new
	end

	def create
		current_user.notes.create(create_note_params)
		redirect_to notes_path
	end

	def destroy
		note = current_user.notes.find(params[:id])
		note.delete
		redirect_to notes_path
	end

	def update
		note = current_user.notes.find(edit_note_params[:id])
		note.update(body: edit_note_params[:note])
	end

	private

	def create_note_params
		params.require(:note).permit(:body)
	end

	def edit_note_params
		params.permit(:note, :id)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
	end

	def new
	end

	def create
		current_user.reviews.create(review_params)
		redirect_to articles_path
	end

	private

	def review_params
		params.permit(:review, :rating, :article_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/news_helper.rb
module NewsHelper

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Reenie+Beanie">
    <link rel="stylesheet" type='text/css' href="https://fonts.googleapis.com/css?family=Poiret+One">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class='nav'>
      <ul>
        <li class='left'><%= link_to "Home", root_path %></li>
        <li class='left'><%= link_to "Articles", articles_path %></li>
        <% if user_signed_in? %>
          <li class='left'><%= link_to "Notes", notes_path %></li>
          <li class='left'><%= link_to "News", news_path %></li>
          <li class='right'><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class='right'><%= link_to "Sign up", new_user_registration_path %></li>
          <li class='right'><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
      </ul>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>